INSERT INTO products (name, price, create_at) VALUES('Panasonic', 800, NOW());
INSERT INTO products (name, price, create_at) VALUES('Sony', 400, NOW());
INSERT INTO products (name, price, create_at) VALUES('Adidas', 80, NOW());
INSERT INTO products (name, price, create_at) VALUES('Vego', 30, NOW());
INSERT INTO products (name, price, create_at) VALUES('Reebok', 40, NOW());
INSERT INTO products (name, price, create_at) VALUES('Apple', 1200, NOW());
INSERT INTO products (name, price, create_at) VALUES('Nike', 100, NOW());
INSERT INTO products (name, price, create_at) VALUES('HP', 850, NOW());
INSERT INTO products (name, price, create_at) VALUES('Asus', 600, NOW());